# Generated by Django 5.0.3 on 2024-03-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("News", "0001_initial"),
        ("Tag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="click_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="news",
            name="tags",
            field=models.ManyToManyField(blank=True, to="Tag.tag"),
        ),
    ]
