# Generated by Django 5.0.3 on 2024-03-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "uid",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="uid"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        default="null", max_length=11, verbose_name="phone"
                    ),
                ),
                ("password", models.CharField(max_length=25, verbose_name="password")),
            ],
        ),
    ]
