# Generated by Django 4.2.4 on 2024-04-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tag_pref",
            field=models.JSONField(blank=True, null=True, verbose_name="tag_pref"),
        ),
    ]
